# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2

defaults: &defaults
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run lint

  test-unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run test:unit

  test-e2e:
    docker:
      - image: cypress/base:8
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run: ./node_modules/.bin/cypress install
      - run: npm run test:e2e

  test-audit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run test:audit

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      # run "$ firebase login:ci" to get your ci token
      # put your token to your circle ci
      - run: npm run fb:deploy

  deploy-prod:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      # run "$ firebase login:ci" to get your ci token
      # put your token to your circle ci
      - run: npm run fb:deploy-prod

workflows:
  version: 2
  pipeline:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - test-unit:
          requires:
            - checkout
      - test-e2e:
          requires:
            - checkout
      - test-audit:
          requires:
            - test-unit
      - build:
          requires:
            - test-unit
            - test-audit
            - lint
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
            - build
      - deploy-prod:
          requires:
            - hold
            - test-e2e
          filters:
            branches:
              only: master
